import * as React from "react";
import VisGraph from "vis-react";
import { NodeTree } from "interfaces/graph";

interface GraphProps {
  tree?: NodeTree;
}

const graph = {
  nodes: [
    { id: 0, label: "test" },
    { id: 1 },
    { id: 2 },
    { id: 3 },
    { id: 4 },
    { id: 5 },
    { id: 6 },
    { id: 7 },
    { id: 8 },
    { id: 9 },
    { id: 10 },
    { id: 11 },
    { id: 12 },
    { id: 13 },
    { id: 14 },
    { id: 15 },
    { id: 16 },
    { id: 17 },
    { id: 18 },
    { id: 19 },
    { id: 20 },
    { id: 21 },
    { id: 22 },
    { id: 23 },
    { id: 24 },
    { id: 25 },
    { id: 26 },
    { id: 27 },
    { id: 28 },
    { id: 29 },
    { id: 30 },
    { id: 31 },
    { id: 32 },
    { id: 33 },
    { id: 34 },
    { id: 35 },
    { id: 36 },
    { id: 37 },
    { id: 38 },
    { id: 39 },
    { id: 40 },
    { id: 41 },
    { id: 42 },
    { id: 43 },
    { id: 44 },
    { id: 45 },
    { id: 46 },
  ],
  edges: [
    { from: 0, to: 1 },
    { from: 0, to: 2 },
    { from: 1, to: 3 },
    { from: 1, to: 4 },
    { from: 2, to: 5 },
    { from: 2, to: 6 },
    { from: 3, to: 7 },
    { from: 3, to: 8 },
    { from: 4, to: 9 },
    { from: 4, to: 10 },
    { from: 5, to: 11 },
    { from: 5, to: 12 },
    { from: 6, to: 13 },
    { from: 6, to: 14 },
    { from: 7, to: 15 },
    { from: 7, to: 16 },
    { from: 8, to: 17 },
    { from: 8, to: 18 },
    { from: 9, to: 19 },
    { from: 9, to: 20 },
    { from: 10, to: 21 },
    { from: 10, to: 22 },
    { from: 11, to: 23 },
    { from: 11, to: 24 },
    { from: 12, to: 25 },
    { from: 12, to: 26 },
    { from: 13, to: 27 },
    { from: 13, to: 28 },
    { from: 14, to: 29 },
    { from: 14, to: 30 },
    { from: 15, to: 31 },
    { from: 16, to: 32 },
    { from: 17, to: 33 },
    { from: 18, to: 34 },
    { from: 19, to: 35 },
    { from: 20, to: 36 },
    { from: 21, to: 37 },
    { from: 22, to: 38 },
    { from: 23, to: 39 },
    { from: 24, to: 40 },
    { from: 25, to: 41 },
    { from: 26, to: 42 },
    { from: 27, to: 43 },
    { from: 28, to: 44 },
    { from: 29, to: 45 },
    { from: 30, to: 46 },
  ],
};

const options = {
  layout: {
    hierarchical: {
      direction: "UD",
      sortMethod: "directed",
    },
  },
  interaction: { dragNodes: false },
  physics: {
    enabled: false,
  },
  configure: {
    filter: (option, path) => path.indexOf("hierarchical") !== -1,
    showButton: false,
  },
};

export const Graph: React.FC<GraphProps> = ({ tree }) => (
  <VisGraph graph={graph} options={options} />
);
